volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: cc-postgres
    image: postgres:14
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Budapest"

  keycloak:
    container_name: cc-keycloak
    image: jboss/keycloak:14.0.0
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres:5432
      DB_DATABASE: keycloak_db
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      TZ: "Europe/Budapest"
    ports:
      - 8080:8080
    depends_on:
      - postgres

  calorie-counter-backend:
    image: calorie-counter-backend
    container_name: cc-backend
    environment:
      TZ: "Europe/Budapest"
    depends_on:
      - postgres
    ports:
      - 8081:8081

  calorie-counter-frontend:
    image: calorie-counter-frontend
    container_name: cc-frontend
    environment:
      TZ: "Europe/Budapest"
    depends_on:
      - postgres
    ports:
      - 3000:3000
