services:
  cc-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calorie-counter-db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
