spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/calorie_counter_db
    username: postgres
    password: admin

  banner:
    location: banner.txt

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: MAG
  resource: login
  public-client: true
