spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: admin

  banner:
    location: banner.txt

server:
  port: 8081

keycloak:
  realm: CC
  resource: login
  public-client: true

cc:
  keycloak:
    client-id: login
    client-secret: 745336ef-996d-4f3a-9484-4e8238273ebc

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/calorie_counter_db

keycloak:
  auth-server-url: http://localhost:8080/auth

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/calorie_counter_db

keycloak:
  auth-server-url: http://host.docker.internal:8080/auth
